from bs4 import BeautifulSoup
import requests

url = "index.html"

soup = BeautifulSoup(open(url, encoding="utf8"), 'html.parser')

list_subject = soup.find_all('tr', class_='row-diem')

count = 7

semester = ["e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39", "9da3175a-c1a0-4b72-a812-cf058b19ca62", "326f3844-05a0-4e36-b935-e41344de0928", "27bb76d1-41df-4198-b5e4-42d592560de3", "a75f647e-7151-40fb-8732-f22aedbc599e", "324475b9-6e53-4f0e-b62a-7a67541c0bec", "62d73a4f-6177-4c5c-9f3a-82341ee9a074", "87367bec-a597-41a6-aaf5-7f320ebfc2a7"]

for data in list_subject:
    code = data.find_all('td')[1].find('span').text
    name = data.find_all('td')[2].find('span').text
    credit = data.find_all('td')[3].find('span').text

    attendancePoint = data.find_all('td')[9].find('span').text
    testPoint = data.find_all('td')[10].find('span').text
    practicePoint = data.find_all('td')[12].find('span').text
    examPoint = data.find_all('td')[13].find('span').text

    try:
        float(attendancePoint)
    except ValueError:
        attendancePoint = "8.0"
    try:
        float(testPoint)
    except ValueError:
        testPoint = "8.0"
    try:
        float(practicePoint)
    except ValueError:
        practicePoint = "8.0"
    try:
        float(examPoint)
    except ValueError:
        examPoint = "8.0"

    semester = int(count/7)
    count+=1

    
    myStr = 'studentGradeService.updateGradeForStudent(StudentGradeReq.builder()\r\n                .studentCode(\"B19DCCN123\")\r\n                .subjectCode(\"' + str(code) + '\")\r\n                .semesterId(\"Học kỳ ' + str(semester) + '\")\r\n                .attendancePoint(' + str(attendancePoint) + ')\r\n                .testPoint(' + str(testPoint) + ')\r\n                .practicePoint(' + str(practicePoint) + ')\r\n                .examPoint(' + str(examPoint) + ')\r\n                .build());'

    print(myStr)
    # str = "subjectRepository.save(new Subject("+'\"'+code+'\"'+", "+'\"'+name+'\"'+", "+credit+"));"
    # print(str)

'''
for (int i = 1; i < 9; i++)
            semesterRepository.save(new Semester("Học kỳ " + i));

        subjectRepository.save(new Subject("BAS1105M", "Giáo dục quốc phòng", 7));
   m,     subjectRepository.save(new Subject("BAS1201", "Đại số", 3));
        subjectRepository.save(new Subject("BAS1150", "Triết học Mác - Lênin", 3));
        subjectRepository.save(new Subject("BAS1105M", "Giáo dục quốc phòng", 7));
        subjectRepository.save(new Subject("BAS1106", "Giáo dục thể chất 1", 2));
        subjectRepository.save(new Subject("INT1154", "Tin học cơ sở 1", 2));
        subjectRepository.save(new Subject("BAS1203", "Giải tích 1", 3));
        subjectRepository.save(new Subject("BAS1141", "Tiếng Anh A11", 3));
        subjectRepository.save(new Subject("BAS1204", "Giải tích 2", 3));
        subjectRepository.save(new Subject("BAS1151", "Kinh tế chính trị Mác- Lênin", 2));
        subjectRepository.save(new Subject("BAS1107", "Giáo dục thể chất 2", 2));
        subjectRepository.save(new Subject("BAS1226", "Xác suất thống kê", 2));
        subjectRepository.save(new Subject("BAS1152", "Chủ nghĩa xã hội khoa học", 2));
        subjectRepository.save(new Subject("INT1155", "Tin học cơ sở 2", 2));
        subjectRepository.save(new Subject("BAS1224", "Vật lý 1 và thí nghiệm", 4));
        subjectRepository.save(new Subject("BAS1122", "Tư tưởng Hồ Chí Minh", 2));
        subjectRepository.save(new Subject("INT1339", "Ngôn ngữ lập trình C++", 3));
        subjectRepository.save(new Subject("BAS1142", "Tiếng Anh A12", 4));
        subjectRepository.save(new Subject("BAS1227", "Vật lý 3 và thí nghiệm", 4));
        subjectRepository.save(new Subject("ELE1433", "Kỹ thuật số", 2));
        subjectRepository.save(new Subject("INT1358", "Toán rời rạc 1", 3));
        subjectRepository.save(new Subject("BAS1153", "Lịch sử Đảng cộng sản Việt Nam", 2));
        subjectRepository.save(new Subject("BAS1143", "Tiếng Anh A21", 3));
        subjectRepository.save(new Subject("INT1359", "Toán rời rạc 2", 3));
        subjectRepository.save(new Subject("ELE1319", "Lý thuyết thông tin", 3));
        subjectRepository.save(new Subject("INT1306", "Cấu trúc dữ liệu và giải thuật", 3));
        subjectRepository.save(new Subject("SKD1103", "Kỹ năng tạo lập Văn bản", 1));
        subjectRepository.save(new Subject("ELE1330", "Xử lý tín hiệu số", 2));
        subjectRepository.save(new Subject("INT13145", "Kiến trúc máy tính", 3));
        subjectRepository.save(new Subject("BAS1122", "Tư tưởng Hồ Chí Minh", 2));
        subjectRepository.save(new Subject("INT1336", "Mạng máy tính", 3));
        subjectRepository.save(new Subject("INT1313", "Cơ sở dữ liệu", 3));
        subjectRepository.save(new Subject("SKD1101", "Kỹ năng thuyết trình", 1));
        subjectRepository.save(new Subject("INT1332", "Lập trình hướng đối tượng", 3));
        subjectRepository.save(new Subject("INT1319", "Hệ điều hành", 3));
        subjectRepository.save(new Subject("BAS1144", "Tiếng Anh A22", 4));
        subjectRepository.save(new Subject("INT13162", "Lập trình với Python", 3));
        subjectRepository.save(new Subject("INT1341", "Nhập môn trí tuệ nhân tạo", 3));
        subjectRepository.save(new Subject("INT13147", "Thực tập cơ sở", 3));
        subjectRepository.save(new Subject("INT1340", "Nhập môn công nghệ phần mềm", 3));
        subjectRepository.save(new Subject("SKD1102", "Kỹ năng làm việc nhóm", 1));
        subjectRepository.save(new Subject("INT14148", "Cơ sở dữ liệu phân tán", 3));
        subjectRepository.save(new Subject("INT1434", "Lập trình Web", 3));
        subjectRepository.save(new Subject("INT1303", "An toàn và bảo mật hệ thống thông tin", 3));
        subjectRepository.save(new Subject("INT13146", "Xử lý ảnh", 3));
        subjectRepository.save(new Subject("INT1342M", "Phân tích và thiết kế hệ thống thông tin", 3));
        subjectRepository.save(new Subject("SKD1108", "Phương pháp luận nghiên cứu khoa học", 2));
        subjectRepository.save(new Subject("INT14149", "IoT và ứng dụng", 3));
        subjectRepository.save(new Subject("INT1404", "Các hệ thống dựa trên tri thức", 3));
        subjectRepository.save(new Subject("INT14150", "Nhập môn khoa học dữ liệu", 3));
        subjectRepository.save(new Subject("INT1450", "Quản lý dự án phần mềm", 2));
'''

'''
studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1105M")
                .semesterName("Học kỳ 1")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1201")
                .semesterName("Học kỳ 1")
                .attendancePoint(10.0)
                .testPoint(6.0)
                .practicePoint(8.0)
                .examPoint(10.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1150")
                .semesterName("Học kỳ 1")
                .attendancePoint(10.0)
                .testPoint(9.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1105M")
                .semesterName("Học kỳ 1")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1106")
                .semesterName("Học kỳ 1")
                .attendancePoint(10.0)
                .testPoint(5.0)
                .practicePoint(8.0)
                .examPoint(2.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1154")
                .semesterName("Học kỳ 1")
                .attendancePoint(10.0)
                .testPoint(5.0)
                .practicePoint(9.0)
                .examPoint(4.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1203")
                .semesterName("Học kỳ 1")
                .attendancePoint(10.0)
                .testPoint(7.0)
                .practicePoint(9.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1141")
                .semesterName("Học kỳ 2")
                .attendancePoint(8.0)
                .testPoint(6.0)
                .practicePoint(3.5)
                .examPoint(6.1)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1204")
                .semesterName("Học kỳ 2")
                .attendancePoint(10.0)
                .testPoint(9.0)
                .practicePoint(10.0)
                .examPoint(9.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1151")
                .semesterName("Học kỳ 2")
                .attendancePoint(9.0)
                .testPoint(7.0)
                .practicePoint(8.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1107")
                .semesterName("Học kỳ 2")
                .attendancePoint(9.0)
                .testPoint(5.0)
                .practicePoint(8.0)
                .examPoint(2.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1226")
                .semesterName("Học kỳ 2")
                .attendancePoint(10.0)
                .testPoint(9.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1152")
                .semesterName("Học kỳ 2")
                .attendancePoint(9.0)
                .testPoint(6.0)
                .practicePoint(8.0)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1155")
                .semesterName("Học kỳ 2")
                .attendancePoint(10.0)
                .testPoint(7.0)
                .practicePoint(9.0)
                .examPoint(9.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1224")
                .semesterName("Học kỳ 3")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(10.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1122")
                .semesterName("Học kỳ 3")
                .attendancePoint(6.0)
                .testPoint(7.5)
                .practicePoint(8.0)
                .examPoint(2.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1339")
                .semesterName("Học kỳ 3")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1142")
                .semesterName("Học kỳ 3")
                .attendancePoint(7.0)
                .testPoint(4.0)
                .practicePoint(6.0)
                .examPoint(5.6)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1227")
                .semesterName("Học kỳ 3")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(9.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("ELE1433")
                .semesterName("Học kỳ 3")
                .attendancePoint(9.0)
                .testPoint(8.5)
                .practicePoint(8.0)
                .examPoint(9.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1358")
                .semesterName("Học kỳ 3")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1153")
                .semesterName("Học kỳ 4")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1143")
                .semesterName("Học kỳ 4")
                .attendancePoint(5.8)
                .testPoint(8.8)
                .practicePoint(7.0)
                .examPoint(7.3)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1359")
                .semesterName("Học kỳ 4")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(8.5)
                .examPoint(9.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("ELE1319")
                .semesterName("Học kỳ 4")
                .attendancePoint(8.0)
                .testPoint(6.0)
                .practicePoint(8.5)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1306")
                .semesterName("Học kỳ 4")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(8.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("SKD1103")
                .semesterName("Học kỳ 4")
                .attendancePoint(9.0)
                .testPoint(6.0)
                .practicePoint(8.0)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("ELE1330")
                .semesterName("Học kỳ 4")
                .attendancePoint(10.0)
                .testPoint(9.0)
                .practicePoint(8.0)
                .examPoint(6.3)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT13145")
                .semesterName("Học kỳ 5")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.3)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1122")
                .semesterName("Học kỳ 5")
                .attendancePoint(10.0)
                .testPoint(8.5)
                .practicePoint(8.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1336")
                .semesterName("Học kỳ 5")
                .attendancePoint(8.0)
                .testPoint(7.5)
                .practicePoint(7.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1313")
                .semesterName("Học kỳ 5")
                .attendancePoint(10.0)
                .testPoint(9.5)
                .practicePoint(9.5)
                .examPoint(9.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("SKD1101")
                .semesterName("Học kỳ 5")
                .attendancePoint(9.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1332")
                .semesterName("Học kỳ 5")
                .attendancePoint(9.0)
                .testPoint(8.5)
                .practicePoint(8.0)
                .examPoint(10.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1319")
                .semesterName("Học kỳ 5")
                .attendancePoint(8.0)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("BAS1144")
                .semesterName("Học kỳ 6")
                .attendancePoint(9.0)
                .testPoint(7.0)
                .practicePoint(6.5)
                .examPoint(7.4)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT13162")
                .semesterName("Học kỳ 6")
                .attendancePoint(10.0)
                .testPoint(8.5)
                .practicePoint(8.0)
                .examPoint(6.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1341")
                .semesterName("Học kỳ 6")
                .attendancePoint(8.0)
                .testPoint(9.5)
                .practicePoint(7.0)
                .examPoint(10.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT13147")
                .semesterName("Học kỳ 6")
                .attendancePoint(9.0)
                .testPoint(6.0)
                .practicePoint(8.0)
                .examPoint(9.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1340")
                .semesterName("Học kỳ 6")
                .attendancePoint(9.0)
                .testPoint(5.0)
                .practicePoint(7.0)
                .examPoint(9.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("SKD1102")
                .semesterName("Học kỳ 6")
                .attendancePoint(8.0)
                .testPoint(7.0)
                .practicePoint(8.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT14148")
                .semesterName("Học kỳ 6")
                .attendancePoint(9.0)
                .testPoint(8.5)
                .practicePoint(8.8)
                .examPoint(4.2)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1434")
                .semesterName("Học kỳ 7")
                .attendancePoint(10.0)
                .testPoint(5.0)
                .practicePoint(8.0)
                .examPoint(8.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1303")
                .semesterName("Học kỳ 7")
                .attendancePoint(7.5)
                .testPoint(7.0)
                .practicePoint(10.0)
                .examPoint(8.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT13146")
                .semesterName("Học kỳ 7")
                .attendancePoint(8.0)
                .testPoint(8.5)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1342M")
                .semesterName("Học kỳ 7")
                .attendancePoint(9.0)
                .testPoint(7.5)
                .practicePoint(7.5)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("SKD1108")
                .semesterName("Học kỳ 7")
                .attendancePoint(6.0)
                .testPoint(7.0)
                .practicePoint(7.5)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT14149")
                .semesterName("Học kỳ 7")
                .attendancePoint(10.0)
                .testPoint(7.0)
                .practicePoint(8.6)
                .examPoint(9.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1404")
                .semesterName("Học kỳ 7")
                .attendancePoint(9.0)
                .testPoint(4.0)
                .practicePoint(4.0)
                .examPoint(5.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT14150")
                .semesterName("Học kỳ 8")
                .attendancePoint(7.0)
                .testPoint(7.8)
                .practicePoint(8.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN279")
                .subjectCode("INT1450")
                .semesterName("Học kỳ 8")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(7.0)
                .build());
'''

'''
studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1105M")
                .semesterId("e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1150")
                .semesterId("e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39")
                .attendancePoint(7.0)
                .testPoint(5.0)
                .practicePoint(8.0)
                .examPoint(2.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1203")
                .semesterId("e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39")
                .attendancePoint(7.0)
                .testPoint(6.0)
                .practicePoint(5.0)
                .examPoint(5.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1154")
                .semesterId("e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(5.0)
                .examPoint(2.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1106")
                .semesterId("e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39")
                .attendancePoint(10.0)
                .testPoint(7.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1201")
                .semesterId("e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39")
                .attendancePoint(9.0)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(7.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1105M")
                .semesterId("e1fbf3d9-28d1-4ab6-baf7-b5a8f2a94c39")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1151")
                .semesterId("9da3175a-c1a0-4b72-a812-cf058b19ca62")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(5.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1224")
                .semesterId("9da3175a-c1a0-4b72-a812-cf058b19ca62")
                .attendancePoint(9.5)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(5.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1141")
                .semesterId("9da3175a-c1a0-4b72-a812-cf058b19ca62")
                .attendancePoint(9.2)
                .testPoint(4.5)
                .practicePoint(5.0)
                .examPoint(5.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1155")
                .semesterId("9da3175a-c1a0-4b72-a812-cf058b19ca62")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(9.0)
                .examPoint(4.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1226")
                .semesterId("9da3175a-c1a0-4b72-a812-cf058b19ca62")
                .attendancePoint(8.0)
                .testPoint(5.0)
                .practicePoint(5.0)
                .examPoint(2.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1204")
                .semesterId("9da3175a-c1a0-4b72-a812-cf058b19ca62")
                .attendancePoint(10.0)
                .testPoint(9.5)
                .practicePoint(10.0)
                .examPoint(1.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1107")
                .semesterId("9da3175a-c1a0-4b72-a812-cf058b19ca62")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(8.0)
                .examPoint(5.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1152")
                .semesterId("326f3844-05a0-4e36-b935-e41344de0928")
                .attendancePoint(9.0)
                .testPoint(6.0)
                .practicePoint(8.0)
                .examPoint(3.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1227")
                .semesterId("326f3844-05a0-4e36-b935-e41344de0928")
                .attendancePoint(9.0)
                .testPoint(7.0)
                .practicePoint(8.0)
                .examPoint(2.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("ELE1433")
                .semesterId("326f3844-05a0-4e36-b935-e41344de0928")
                .attendancePoint(7.5)
                .testPoint(7.5)
                .practicePoint(8.0)
                .examPoint(3.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1358")
                .semesterId("326f3844-05a0-4e36-b935-e41344de0928")
                .attendancePoint(10.0)
                .testPoint(10.0)
                .practicePoint(9.5)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1122")
                .semesterId("326f3844-05a0-4e36-b935-e41344de0928")
                .attendancePoint(8.0)
                .testPoint(7.0)
                .practicePoint(8.0)
                .examPoint(3.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1142")
                .semesterId("326f3844-05a0-4e36-b935-e41344de0928")
                .attendancePoint(8.0)
                .testPoint(3.0)
                .practicePoint(6.0)
                .examPoint(5.1)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1339")
                .semesterId("326f3844-05a0-4e36-b935-e41344de0928")
                .attendancePoint(6.0)
                .testPoint(6.0)
                .practicePoint(8.0)
                .examPoint(0.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1306")
                .semesterId("27bb76d1-41df-4198-b5e4-42d592560de3")
                .attendancePoint(8.0)
                .testPoint(4.0)
                .practicePoint(8.0)
                .examPoint(4.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("ELE1330")
                .semesterId("27bb76d1-41df-4198-b5e4-42d592560de3")
                .attendancePoint(9.0)
                .testPoint(8.5)
                .practicePoint(9.0)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT13145")
                .semesterId("27bb76d1-41df-4198-b5e4-42d592560de3")
                .attendancePoint(9.0)
                .testPoint(6.5)
                .practicePoint(8.0)
                .examPoint(4.7)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("SKD1103")
                .semesterId("27bb76d1-41df-4198-b5e4-42d592560de3")
                .attendancePoint(9.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1143")
                .semesterId("27bb76d1-41df-4198-b5e4-42d592560de3")
                .attendancePoint(5.0)
                .testPoint(8.0)
                .practicePoint(6.0)
                .examPoint(5.6)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1153")
                .semesterId("27bb76d1-41df-4198-b5e4-42d592560de3")
                .attendancePoint(10.0)
                .testPoint(9.0)
                .practicePoint(8.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1359")
                .semesterId("27bb76d1-41df-4198-b5e4-42d592560de3")
                .attendancePoint(10.0)
                .testPoint(9.0)
                .practicePoint(9.5)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("ELE1319")
                .semesterId("a75f647e-7151-40fb-8732-f22aedbc599e")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(3.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1226")
                .semesterId("a75f647e-7151-40fb-8732-f22aedbc599e")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(9.0)
                .examPoint(6.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1339")
                .semesterId("a75f647e-7151-40fb-8732-f22aedbc599e")
                .attendancePoint(10.0)
                .testPoint(6.0)
                .practicePoint(8.0)
                .examPoint(5.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1332")
                .semesterId("a75f647e-7151-40fb-8732-f22aedbc599e")
                .attendancePoint(9.0)
                .testPoint(1.5)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("BAS1144")
                .semesterId("a75f647e-7151-40fb-8732-f22aedbc599e")
                .attendancePoint(5.5)
                .testPoint(9.1)
                .practicePoint(5.0)
                .examPoint(7.4)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1313")
                .semesterId("a75f647e-7151-40fb-8732-f22aedbc599e")
                .attendancePoint(10.0)
                .testPoint(2.0)
                .practicePoint(5.0)
                .examPoint(6.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1336")
                .semesterId("a75f647e-7151-40fb-8732-f22aedbc599e")
                .attendancePoint(6.0)
                .testPoint(9.0)
                .practicePoint(4.5)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("SKD1101")
                .semesterId("324475b9-6e53-4f0e-b62a-7a67541c0bec")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT13162")
                .semesterId("324475b9-6e53-4f0e-b62a-7a67541c0bec")
                .attendancePoint(10.0)
                .testPoint(7.0)
                .practicePoint(8.0)
                .examPoint(4.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1319")
                .semesterId("324475b9-6e53-4f0e-b62a-7a67541c0bec")
                .attendancePoint(8.5)
                .testPoint(7.5)
                .practicePoint(8.0)
                .examPoint(7.1)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1340")
                .semesterId("324475b9-6e53-4f0e-b62a-7a67541c0bec")
                .attendancePoint(5.0)
                .testPoint(0.0)
                .practicePoint(2.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1434")
                .semesterId("324475b9-6e53-4f0e-b62a-7a67541c0bec")
                .attendancePoint(6.0)
                .testPoint(4.0)
                .practicePoint(8.0)
                .examPoint(0.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT13147")
                .semesterId("324475b9-6e53-4f0e-b62a-7a67541c0bec")
                .attendancePoint(0.0)
                .testPoint(0.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1341")
                .semesterId("324475b9-6e53-4f0e-b62a-7a67541c0bec")
                .attendancePoint(7.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(3.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT14148")
                .semesterId("62d73a4f-6177-4c5c-9f3a-82341ee9a074")
                .attendancePoint(9.0)
                .testPoint(7.5)
                .practicePoint(6.0)
                .examPoint(3.3)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("SKD1102")
                .semesterId("62d73a4f-6177-4c5c-9f3a-82341ee9a074")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1303")
                .semesterId("62d73a4f-6177-4c5c-9f3a-82341ee9a074")
                .attendancePoint(8.0)
                .testPoint(1.0)
                .practicePoint(1.0)
                .examPoint(5.5)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("ELE1433")
                .semesterId("62d73a4f-6177-4c5c-9f3a-82341ee9a074")
                .attendancePoint(9.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(3.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("SKD1108")
                .semesterId("62d73a4f-6177-4c5c-9f3a-82341ee9a074")
                .attendancePoint(9.0)
                .testPoint(7.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1342M")
                .semesterId("62d73a4f-6177-4c5c-9f3a-82341ee9a074")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(6.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1433")
                .semesterId("62d73a4f-6177-4c5c-9f3a-82341ee9a074")
                .attendancePoint(9.0)
                .testPoint(2.0)
                .practicePoint(3.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT14149")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(7.0)
                .practicePoint(5.0)
                .examPoint(2.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT13146")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(9.5)
                .testPoint(7.5)
                .practicePoint(9.0)
                .examPoint(7.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1450")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(8.5)
                .examPoint(6.4)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT14151")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(10.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(5.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1448")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1416")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1408")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1461")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1427")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT1449")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
        studentGradeService.updateGradeForStudent(StudentGradeReq.builder()
                .studentCode("B19DCCN123")
                .subjectCode("INT13147")
                .semesterId("87367bec-a597-41a6-aaf5-7f320ebfc2a7")
                .attendancePoint(8.0)
                .testPoint(8.0)
                .practicePoint(8.0)
                .examPoint(8.0)
                .build());
'''